machine:
  image: 'ubuntu-2004:202107-02'
working_directory: ~/boundary
steps:
- checkout
- run:
    name: "Install Tools"
    command: |
      make golangci-lint
- run:
    name: "Lint"
    no_output_timeout: 15m
    command: |
      make lint
- slack/status:
    fail_only: true
    only_for_branches: master
    webhook: webhook
