machine:
  image: 'ubuntu-2004:202107-02'
working_directory: ~/boundary
parameters:
  postgres-version:
    type: string
steps:
- checkout
- run:
    name: "Run SQL PgTap Tests"
    command: |
      make test-sql POSTGRES_DOCKER_IMAGE_BASE=docker.mirror.hashicorp.services/postgres PG_DOCKER_TAG=<< parameters.postgres-version >>
